version: '3.7'
services:
  app:
    build: .
    links:
      - yourlist
    ports:
      - "5000:5000"
    depends_on:
      - yourlist

  yourlist:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/backend/mysql:/docker-entrypoint-initdb.d/:ro
